services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: "8080"
      BASE_URL: "http://localhost:8080"
      LOG_LEVEL: "info"
      DB_DSN: "postgres://comment_tree_user:comment_tree_password@db:5432/comment_tree?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.10-alpine
    environment:
      POSTGRES_USER: comment_tree_user
      POSTGRES_PASSWORD: comment_tree_password
      POSTGRES_DB: comment_tree
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
      - ./migrations:/migrations:ro

volumes:
  db_data: